pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        mavenCentral()
    }
}

rootProject.name = 'octane'

include 'common'
include 'fabric'
include 'neoforge-stub'
include 'forge-stub'
